algoritmo "produtoComDesconto"

var
valorProduto, valorDesconto, valorProdutoComDesconto : real
inicio
escreval ("Seja bem vindo!")
escreval("Informe valor do produto")
leia (valorProduto)
escreval("Informe a porcentagem de desconto que será feita no produto")
leia (valorDesconto)
valorProdutoComDesconto <- valorproduto - ((valorproduto *  valordesconto) /100)
escreval("O produto com desconto fica: ",valorProdutoComDesconto," reais")

fimalgoritmo
